// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PhotoGallery.Models;

[Table("Image")]
public partial class Image
{
    [Key]
    public int Id { get; set; }

    [InverseProperty("IdNavigation")]
    public virtual Photo Photo { get; set; }

    [InverseProperty("IdNavigation")]
    public virtual Thumbnail Thumbnail { get; set; }
}