// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PhotoGallery.Models;

[Table("Thumbnail")]
public partial class Thumbnail
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(128)]
    public string Filename { get; set; }

    [Required]
    public string Url { get; set; }

    [ForeignKey("Id")]
    [InverseProperty("Thumbnail")]
    public virtual Image IdNavigation { get; set; }
}